DATOS SEGMENT
	TABLA DB 3FH, 06H, 5BH, 4FH, 66H, 6DH, 7DH, 07H, 7FH, 67H, 77H, 7CH, 39H, 5EH, 79H, 71H
;                 0    1    2    3    4    5    6    7    8    9    A    B    C    D    E    F
DATOS ENDS

CODIGO SEGMENT
  ASSUME CS:CODIGO, DS:DATOS

INICIO:	MOV AX, DATOS
	MOV DS, AX

CERO:	MOV CL, 0
	MOV CH, 0	;Indicador 0 para incremento, 1 para decremento

INIC2:	CMP CH, 0
	JE INCRE
	JMP DECRE

INCRE:	CMP CL, 15
	JE OTRO1
	INC CL
	CALL VISUAL
	CALL RETARD
	JMP INIC2

OTRO1:	MOV CH, 1
	JMP INIC2

DECRE:	CMP CL, 0
	JE OTRO2
	DEC CL
	CALL VISUAL
	CALL RETARD
	JMP INIC2

OTRO2:	MOV CH, 0
	JMP INIC2

VISUAL:	MOV DX, OFFSET TABLA
	MOV SI, DX
	MOV BL, CL
	MOV BH, 0
	MOV AL, BYTE PTR[SI+BX]
	MOV DX, 378H
	OUT DX, AL
	RET

RETARD:	PUSH AX
	PUSH BX
	PUSH CX
	MOV AX, 1000
P3:	MOV BX, 1000
P2:	MOV CX, 300
P1:	DEC CX
	JNZ P1
	DEC BX
	JNZ P2
	DEC AX
	JNZ P3
	POP CX
	POP BX
	POP AX
	RET

	CODIGO ENDS

END INICIO
