DATOS SEGMENT
	TITULO DB "INGRESAR NUMEROS:", 0AH,0DH, "$"
	INGRES DB 10,0,10 DUP("*")
	VAR1 DW ?
	VAR2 DW ?
	TEMP DW ?
DATOS ENDS

CODIGO SEGMENT
  ASSUME CS:CODIGO,DS:DATOS

INICIO:
	MOV AX,DATOS
	MOV DS, AX
	MOV AH,09H
	LEA DX,TITULO
	INT 21H
	MOV AH,0AH
	LEA DX, INGRES
	INT 21H
	MOV SI,DX
	ADD SI,2
 
DNUEVO:	MOV TEMP,0
	MOV CX,6

LAZO:	MOV VAR1,BYTE PTR[SI+TEMP]
	MOV VAR2,BYTE PTR[SI+1+TEMP]
	CMP VAR2,VAR1
	JLE ORDN
	MOV BYTE PTR[SI+TEMP],VAR2
	MOV BYTE PTR[SI+1+TEMP],VAR1
	JMP DNUEVO

ORDN:	ADD TEMP,1
	LOOP LAZO

	MOV AH,09H
	LEA DX,INGRES
	MOV SI,DX
	MOV BL, BYTE PTR[SI+1]
	MOV BH,0
	MOV BYTE PTR[SI+BX+2],"$"
	ADD DX, 2
	INT 21H


FIN:	MOV AH,4CH
	INT 21H

CODIGO ENDS
	END INICIO
