DATOS SEGMENT
	TITULO DB "INGRESAR NUMEROS:", 0AH,0DH, "$"
	SALTO DB 0AH,0DH,"$"
	INGRES DB 8,0,10 DUP("*")
	TEMP DW ?
DATOS ENDS

CODIGO SEGMENT
  ASSUME CS:CODIGO,DS:DATOS

INICIO:
	MOV AX,DATOS
	MOV DS, AX
	MOV AH,09H
	LEA DX,TITULO
	INT 21H
	MOV AH,0AH
	LEA DX,INGRES
	INT 21H
	MOV SI,DX
	MOV BL,BYTE PTR[SI+1]
	MOV BH,0
	
 
DNUEVO:	MOV TEMP,0
	MOV CX,BX

LAZO:	MOV AL,BYTE PTR[SI+2+TEMP]
	MOV BL,BYTE PTR[SI+3+TEMP]
	CMP BL,AL
	JLE ORDN
	MOV BYTE PTR[SI+TEMP],BL
	MOV BYTE PTR[SI+1+TEMP],AL
	JMP DNUEVO

ORDN:	ADD TEMP,1
	LOOP LAZO

	MOV AH,09H
	LEA DX,SALTO
	INT 21H
	LEA DX,INGRES
	MOV SI,DX
	MOV BL, BYTE PTR[SI+1]
	MOV BH,0
	MOV BYTE PTR[SI+BX+2],"$"
	ADD DX, 2
	INT 21H

FIN:	MOV AH,4CH
	INT 21H

CODIGO ENDS
	END INICIO
