DATOS SEGMENT
  CADE1 DB "Ingrese clave:", 0AH, 0DH, "$"
  CLAVE DB "cesar"
  INCLA DB "*****$"
  CORRT DB 0AH, 0DH, "Clave correcta!$"
  INCOR DB 0AH, 0DH, "Clave incorrecta!, ingrese de nuevo", 0AH, 0DH, "$"
DATOS ENDS

CODIGO SEGMENT
  ASSUME CS:CODIGO, DS:DATOS

INICIO:	MOV AX, DATOS
	MOV DS, AX
	MOV AH, 09H
	LEA DX, CADE1 		;Imprimir la cadena de titulo
	INT 21H
	MOV BX, 0

INGRES:	MOV AH, 07H		;Ingresando un caracter sin eco
	INT 21H
	LEA DX, INCLA
	MOV SI, DX
	MOV BYTE PTR[SI+BX], AL
	MOV AH, 02H
	MOV DL, '*'
	INT 21H
	CMP BX, 4
	JE OTRO
	INC BX
	JMP INGRES

OTRO:	MOV BX, 0
OTRO1:	LEA DX, CLAVE
	MOV SI, DX 
	MOV CL, BYTE PTR[SI+BX]
	LEA DX, INCLA
	MOV SI, DX
	MOV CH, BYTE PTR[SI+BX]
	CMP CL, CH
	JE VERDAD
	JMP NOOOO

VERDAD:	CMP BX, 4
	JE SIIII
	INC BX
	JMP OTRO1
	
SIIII:	MOV AH, 09H
	LEA DX, CORRT
	INT 21H
	JMP FIN

NOOOO:	MOV AH, 09H
	LEA DX, INCOR
	INT 21H
	JMP INICIO

FIN:	MOV AH, 4CH
	INT 21H

	CODIGO ENDS

END INICIO



