;Este es un programa para titilar un LED por un pin del puerto paralelo
;Con la tecla 'y' titilamos el LED y con la tecla 'n' apagamos el LED
;Con la tecla 'q' salimos de la aplicacion

DATOS SEGMENT
	TIT1 DB "PROGRAMA PARA TITILAR UN LED", "$" 
	OPT DB 0AH, 0DH, "ELIJA OPCION ('y' TITILAR, 'q' SALIR): ", "$"
	ONLED DB 0AH, 0DH, "EL LED TA TITILANDO PS", "$" 
	OFFLED DB 0AH, 0DH, "EL LED YA NO TA TITILANDO PS", "$" 
	ERRA DB 0AH, 0DH, "TECLA PRESIONADA INCORRECTA, INTENTE DE NUEVO", "$"
	CHAU DB 0AH, 0DH, "GRACIAS POR USAR EL PROGRAMA CHAUFAS", "$" 
DATOS ENDS

CODIGO SEGMENT
  ASSUME CS:CODIGO, DS:DATOS

INICIO:	MOV AX, DATOS
	MOV DS, AX
	MOV AH, 09H
	LEA DX, TIT1
	INT 21H

TECLA:	MOV AH, 09H
	LEA DX, OPT
	INT 21H
	MOV AH, 01H	;SERVICIO PARA LEER UNA TECLA
	INT 21H
	CMP AL, 'y'
	JE TTLE		;SALTO PARA TITILEAR LED
	CMP AL, 'q'
	JE BYEBYE	;SALTO PARA  SALIR DEL PROGRAMA
ERROR:	MOV AH, 09H
	LEA DX, ERRA
	INT 21H
	JMP TECLA

TTLE:	MOV AH, 09H
	LEA DX, ONLED
	INT 21H

	MOV CX, 20
LAZO:	MOV DX, 378H
	MOV AL, 0
	OUT DX, AL	
	CALL RETAR
	MOV AL, 1
	OUT DX, AL	
	CALL RETAR
	LOOP LAZO

	MOV AH, 09H
	LEA DX, OFFLED
	INT 21H
	JMP TECLA
	
RETAR:	PUSH AX
	PUSH BX
	PUSH CX
	MOV AX, 1000
P3:	MOV BX, 1000
P2:	MOV CX, 100
P1:	DEC CX
	JNZ P1
	DEC BX
	JNZ P2
	DEC AX
	JNZ P3
	POP CX
	POP BX
	POP AX
	RET

BYEBYE: MOV AH, 09H
	LEA DX, CHAU
	INT 21H
	MOV AH, 4CH
	INT 21H

CODIGO ENDS
	END INICIO
